title: "WAPPAC Competition"
description: "WavePiston Passive Control competition docs"
theme: just-the-docs

# Local preview:
url: ""
baseurl: ""

# Keep gemfile/Gemfile.lock out of the build
exclude:
  - Gemfile
  - Gemfile.lock
