# The title of your site
title: WAPPAC Competition

# The URL of your site
url: https://emg-mu.github.io/test_web_page.github.io

# The theme
theme: just-the-docs

# Main navigation
nav_pages:
  - title: Home
    permalink: /
  - title: Competition Rules
    permalink: /rules

# Aux links (in the top right)
aux_links:
  WAPPAC on GitHub: https://github.com/emg-mu/test_web_page.github.io
